<a href="https://colab.research.google.com/github/dajebbar/ML/blob/main/NN_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# sigmoid function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# derivative of sigmoid function
def sigmoid_derivative(x):
  return x * (1 - x)

In [3]:
# Neural Network class

class NeuralNetwork:

  def __init__(self, x, y):
    self.x = x
    self.y = y
    self.weights_1 = np.random.rand(self.x.shape[1], 4)
    self.weights_2 = np.random.rand(4, 1)
    self.output = np.zeros(self.y.shape)
  
  def forward_propagation(self):
    self.layer_1 = sigmoid(np.dot(self.x, self.weights_1))
    self.output = sigmoid(np.dot(self.layer_1, self.weights_2))
  
  def backward_propagation(self):
    d_weights_2 = np.dot(
        self.layer_1.T,
        (2 * (self.y - self.output) * sigmoid_derivative(self.output))
    )

    d_weights_1 = np.dot(
        self.x.T,
        (np.dot(2 * (self.y - self.output) * sigmoid_derivative(self.output),
                self.weights_2.T
                ) * sigmoid_derivative(self.layer_1))
    )

    self.weights_1 = self.weights_1 + d_weights_1
    self.weights_2 = self.weights_2 + d_weights_2
  
  def display_infos(self):
    print('X:\n', self.x)
    print()
    print('y:\n', self.y)
    print()
    print('weights L1:\n', self.weights_1)
    print()
    print('weights L2:\n', self.weights_2)
    print()
    print('Preds(outputs): \n', self.output)


  

  


In [4]:
X = np.array([
              [0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]
])

y = np.array([
              [0],
              [1],
              [1],
              [0]
])

In [5]:
nn = NeuralNetwork(X, y)

for i in range(10000):
  nn.forward_propagation()
  nn.backward_propagation()

nn.display_infos()
print('=*=' * 10)
print('Preds Result: ', nn.output)

X:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

y:
 [[0]
 [1]
 [1]
 [0]]

weights L1:
 [[ 2.13056006  4.60744983  7.16862982  2.3700207 ]
 [ 3.91234777 -3.45453198  6.41693304  4.13256585]
 [-4.55005298  2.36772311 -3.07085888 -4.90631324]]

weights L2:
 [[-6.44700659]
 [-5.74735238]
 [11.7450224 ]
 [-7.10821598]]

Preds(outputs): 
 [[0.0077371 ]
 [0.99560446]
 [0.99153214]
 [0.00661389]]
=*==*==*==*==*==*==*==*==*==*=
Preds Result:  [[0.0077371 ]
 [0.99560446]
 [0.99153214]
 [0.00661389]]
