<a href="https://colab.research.google.com/github/dajebbar/ML/blob/main/NN_Demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# sigmoid function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# derivative of sigmoid function
def sigmoid_derivative(x):
  return x * (1 - x)

In [3]:
# Neural Network class

class NeuralNetwork:

  def __init__(self, x, y):
    self.x = x
    self.y = y
    self.weights_1 = np.random.rand(self.x.shape[1], 4)
    self.weights_2 = np.random.rand(4, 1)
    self.output = np.zeros(self.y.shape)
  
  def forward_propagation(self):
    self.layer_1 = sigmoid(self.x @ self.weights_1)
    self.output = sigmoid(self.weights_1 @ self.weights_2)
  
  def backward_propagation(self):
    d_weights_2 = np.dot(
        self.layer_1.T,
        (2 * (self.y - self.output) * sigmoid_derivative(self.output))
    )

    d_weights_1 = np.dot(
        self.x.T,
        (np.dot(2 * (self.y - self.output) * sigmoid_derivative(self.output),
                self.weights_2.T
                ) * sigmoid_derivative(self.layer_1))
    )

    self.weights_1 = self.weights_1 + d_weights_1
    self.weights_2 = self.weights_2 + d_weights_2
  
  def display_infos(self):
    print('X:\n', self.x)
    print()
    print('y:\n', self.y)
    print()
    print('weights L1:\n', self.weights_1)
    print()
    print('weights L2:\n', self.weights_2)
    print()
    print('Preds(outputs): \n', self.output)


  

  


In [4]:
X = np.array([
              [0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]
])

y = np.array([
              [0],
              [1],
              [1],
              [0]
])

In [5]:
nn = NeuralNetwork(X, y)
nn.display_infos()
# for i in range(10000):
#   nn.forward_propagation()
#   nn.backward_propagation()

# print(nn.output)

X:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

y:
 [[0]
 [1]
 [1]
 [0]]

weights L1:
 [[0.09761368 0.10676897 0.97143099 0.82004842]
 [0.41376599 0.69072509 0.51276142 0.17538403]
 [0.56195839 0.49978858 0.81464773 0.06059647]]

weights L2:
 [[0.37674774]
 [0.35833144]
 [0.68129324]
 [0.52233842]]

Preds(outputs): 
 [[0.]
 [0.]
 [0.]
 [0.]]
